
primaryColor = "#1e1e2f"  # Dark navy blue
backgroundColor = "#000000"  # Black
secondaryBackgroundColor = "#1e1e2f"  # Dark navy blue for secondary background
textColor = "#FFFFFF"  # White text
font = "sans serif"
